version: 0.1

default:
  global:
    parameters:
      stack_name: demo-stack
  build:
    parameters:
      cached: true
      parallel: true
  validate:
    parameters:
      lint: true
  deploy:
    parameters:
      capabilities: CAPABILITY_NAMED_IAM
      confirm_changeset: true
      image_repositories: []
      s3_prefix: demo-stack
      region: us-east-1
      resolve_s3: true
  package:
    parameters:
      region: us-east-1
      resolve_s3: true
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: EAGER
  local_start_lambda:
    parameters:
      warm_containers: EAGER
