AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation Tag Provider

Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNCustomTagProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Sid: ProviderUsed
            Action:
              - tag:GetTagKeys
              - tag:GetTagValues
              - tag:TagResources
              - tag:UntagResources
            Resource: '*'
          - Effect: Allow
            Sid: GeneratedTagActionsFromAPI
            Action: "*"
            Resource:
              - '*'
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  CFNTagProvider:
    Type: AWS::Serverless::Function
    Properties:
      Description: CloudFormation Tag Provider
      CodeUri: src/
      FunctionName: cfn-tag-provider
      Handler: provider.handler
      Timeout: 600
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.12

Outputs:
  CFNTagProvider:
    Description: The Lambda function for the CloudFormation Tag Provider
    Value: !GetAtt CFNTagProvider.Arn
    Export:
      Name: CFNTagProvider
